services:
  nginx:
    container_name: hkh_nginx
    image: nginx
    ports:
      - 28001:80
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - /mnt/disk/geodata/hkh/data/stac/:/usr/share/nginx/data/
